# Generated by Django 4.1.1 on 2022-09-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_created_time_listing_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bider',
            new_name='bidder',
        ),
    ]
